# Generated by Django 4.1.3 on 2023-03-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(blank=True, to='main.skills'),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Confident', 'Confident'), ('Professional', 'Professional')], default='Confident', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_intro',
            field=models.CharField(max_length=500),
        ),
    ]
